[package]
name = "leetcode_rust"
version = "0.1.0"
authors = [ "gwy15 <gwy15thu@gmail.com>",]
edition = "2018"

[dependencies]
rand = "0.7.3"
log = "0.4.14"
pretty_env_logger = "0.4.0"

[lib]
path = "067. 最大的异或.rs"
